env:
  global:
    - DB=postgresql
    - CI_NODE_TOTAL=20
  matrix:
    - CI_NODE_INDEX=0
    - CI_NODE_INDEX=1
    - CI_NODE_INDEX=2
    - CI_NODE_INDEX=3
    - CI_NODE_INDEX=4
    - CI_NODE_INDEX=5
    - CI_NODE_INDEX=6
    - CI_NODE_INDEX=7
    - CI_NODE_INDEX=8
    - CI_NODE_INDEX=9
    - CI_NODE_INDEX=10
    - CI_NODE_INDEX=11
    - CI_NODE_INDEX=12
    - CI_NODE_INDEX=13
    - CI_NODE_INDEX=14
    - CI_NODE_INDEX=15
    - CI_NODE_INDEX=16
    - CI_NODE_INDEX=17
    - CI_NODE_INDEX=18
    - CI_NODE_INDEX=19
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install imagemagick libmagickwand-dev -qq -y
branches:
  only:
    - 'master'
    - 'production'
    - 'add-knapsack-gem'
    - /^[0-9]+\.[0-9]+$/
rvm:
  - 2.1.4
before_script:
  - "cp config/database.yml.$DB config/database.yml"
  - "bundle exec rake db:create RAILS_ENV=test"
  - "bundle exec rake db:schema:load RAILS_ENV=test"
  - "bundle exec rake db:seed RAILS_ENV=test"
  - "sh -e /etc/init.d/xvfb start"
script: "bundle exec rake travis"
addons:
  code_climate:
    repo_token:
      secure: "RQcqTqhx9hhcWO97ib8s8I8m/ufPbBuKRfEEh4RHNIsBEMpqekaPNHtK+T2ym2pfbCpD+L+0bZ+nMlSCrYz0gklfNnYJlPH4/g1f0SX2OEdq2eUCi9xlRObi9ayXsz7Ujtk14mncNGx+e02TnAtEjtFBT8uyvxn8Ql4djvOTsCg="
notifications:
  hipchat:
    secure: "Ab0VryffWSq0wgEyvrtQB8JD1m6ZcP5zBKDZxniu4avdT16UuDmiDEIVNCnbm5IEwXjugy/WuKsvczxX+4bOoNW6rJfJTotQAbeT3ZdgIHIr+umzUwRPSHqfCp7eztACeYaIin7BmDLNS2W3GQELMvgjsCPs7cGUYeLjNLqs0RE="
